/* generated by scripts/assemble-guest.mjs — do not edit */
export const GUEST_WASM_BASE64 =
  "AGFzbQEAAAABFANgAn9/AGAEf39/fwF/YAJ/fwF/AkAFBGhvc3QEZWNobwAABGhvc3QFd3JpdGUAAQRob3N0BHJlYWQAAARob3N0BmFwcGVuZAABBGhvc3QEbGlzdAACAwYFAAEAAQIFAwEAAQdEBgZtZW1vcnkCAAhydW5fZWNobwAFCXJ1bl93cml0ZQAGCHJ1bl9yZWFkAAcKcnVuX2FwcGVuZAAICHJ1bl9saXN0AAkKNgUIACAAIAEQAAsMACAAIAEgAiADEAELCAAgACABEAILDAAgACABIAIgAxADCwgAIAAgARAECw==";

export function guestWasmBytes(): Uint8Array {
  const bin = atob(GUEST_WASM_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
