/* generated by scripts/assemble-guest.mjs — do not edit */
export const GUEST_WASM_BASE64 =
  "AGFzbQEAAAABDgJgAn9/AGAEf39/fwF/AhoCBGhvc3QEZWNobwAABGhvc3QFd3JpdGUAAQMDAgABBQMBAAEHIQMGbWVtb3J5AgAIcnVuX2VjaG8AAglydW5fd3JpdGUAAwoXAggAIAAgARAACwwAIAAgASACIAMQAQs=";

export function guestWasmBytes(): Uint8Array {
  const bin = atob(GUEST_WASM_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
  return out;
}
