[package]
name = "imperium-core"
version = "0.1.0-dev"
edition = "2021"
license = "BSL-1.0"
description = "Core types for IMPERIUM"
repository = "https://github.com/aquinoc627-lab/imperium"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
ulid = { workspace = true }
chrono = { version = "0.4", features = ["serde", "clock"] }
bytes = { workspace = true }
zeroize = { workspace = true }
secrecy = { workspace = true }
blake3 = "1"
